name: Preflight

on:
  pull_request:

env:
  APPMAP_TELEMETRY_DISABLED: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # This is needed to see the version history, because
          # checkout action doesn't fetch the base or head branches
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Install and configure AppMap
        uses: getappmap/install-appmap-action@v1-pre.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-type: pip
          build-file: requirements-dev.txt
          verbose: true

      - name: Run tests
        run: python3 -m pytest --cache-clear tests/unit_tests/prompter/test_prompter.py || true
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

      - name: Preflight
        uses: getappmap/preflight-appmap-action@v1-pre.7
        with:
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true
